# Generated by Django 2.0.5 on 2019-01-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=10)),
                ('bitly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortner.Bitly')),
            ],
        ),
    ]
