# Generated by Django 2.0.5 on 2019-01-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short',
            name='bitly',
        ),
        migrations.AddField(
            model_name='bitly',
            name='keys',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='short',
        ),
    ]
